version: "3.8"

services:
  webapp:
    build:
      context: front
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "8081:8081"
    volumes:
      - ./front:/webapp
    depends_on:
      - amadeus
  postgres:
    image: postgres
    restart: unless-stopped
    network_mode: "host"
    environment:
      - POSTGRES_USER=amadeus
      - POSTGRES_PASSWORD=amadeusPassword
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:

# host network means that the proxy in front/src/projects/host/proxy.conf.json should be set to 127.0.0.1
