version: "3.8"

services:
  webapp:
    build: front
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - amadeus
  amadeus:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE__SERVER=postgres
      - DATABASE__USER_ID=amadeus
      - DATABASE__PASSWORD=amadeusPassword
    ports:
      - "8081:80"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=amadeus
      - POSTGRES_PASSWORD=amadeusPassword
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
